version: "3"
services:
  pgdb:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=tilios
      - POSTGRES_PASSWORD=thefirst
      - POSTGRES_DB=lune_search_dev
  persist:
    build:
      context: ./services/Persist/
      dockerfile: Dockerfile
    image: searchpersistdev
    container_name: "search_persist"
    ports:
      - "3333:3333"
    environment: 
      - PG_USER=tilios
      - PG_PASS=thefirst
      - PG_HOST=pgdb
      - PG_DB=lune_search_dev
      - EMAIL_BASE=email
    depends_on: 
      - pgdb
  auth:
    build:
      context: ./services/Auth/
      dockerfile: Dockerfile
    image: searchauthdev
    container_name: "search_auth"
    ports:
      - "4444:4444"
    environment: 
      - EMAIL_BASE=email
      - PERSIST_BASE=persist
  email:
    build:
      context: ./services/Email/
      dockerfile: Dockerfile
    image: searchemaildev
    container_name: "search_email"
    ports:
      - "2222:2222"
    environment: 
      - AUTH_BASE=auth
  questions:
    build:
      context: ./services/Questions/
      dockerfile: Dockerfile
    image: searchquestionsdev
    container_name: "search_questions"
    ports:
      - "7654:7654"
    environment: 
      - PERSIST_BASE=persist
volumes:
  my_dbdata: