apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: email
  name: email
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: email
    spec:
      containers:
      - env:
        - name: AUTH_BASE
          value: auth
        image: searchemaildev
        name: search_email
        ports:
        - containerPort: 2222
        resources: {}
      restartPolicy: Always
status: {}
