apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: persist
  name: persist
spec:
  ports:
  - name: "3333"
    port: 3333
    targetPort: 3333
  selector:
    io.kompose.service: persist
status:
  loadBalancer: {}
