apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: pgdb
  name: pgdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgdb
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: lune_search_dev
        - name: POSTGRES_PASSWORD
          value: thefirst
        - name: POSTGRES_USER
          value: tilios
        image: postgres:11
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: my-dbdata
      restartPolicy: Always
      volumes:
      - name: my-dbdata
        persistentVolumeClaim:
          claimName: my-dbdata
status: {}
