apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: questions
  name: questions
spec:
  ports:
  - name: "7654"
    port: 7654
    targetPort: 7654
  selector:
    io.kompose.service: questions
status:
  loadBalancer: {}
