apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: questions
  name: questions
spec:
  ports:
  - name: "7654"
    port: 7654
    targetPort: 7654
  selector:
    io.kompose.service: questions
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: questions
  name: questions
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: questions
    spec:
      containers:
      - env:
        - name: PERSIST_BASE
          value: persist
        image: searchquestionsdev
        name: search_questions
        ports:
        - containerPort: 7654
        resources: {}
      restartPolicy: Always
status: {}
